# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Create dummy file
        run: |
          touch outputs.json
          echo "{\"auto-builder-stack-enhancedApp-stg-DOP-3977-queues\":{\"ExportsOutputRefqueuesJobUpdatesQueue6072541528F20E74\":\"https://sqs.us-east-2.amazonaws.com/***/auto-builder-stack-enhancedApp-stg-DO-queuesJobUpdatesQueue60725415-547DEZGjtnaD\",\"ExportsOutputFnGetAttqueuesJobUpdatesQueue60725415ArnAF8A3BA3\":\"arn:aws:sqs:us-east-2:***:auto-builder-stack-enhancedApp-stg-DO-queuesJobUpdatesQueue60725415-547DEZGjtnaD\",\"ExportsOutputRefqueuesJobsQueue07E5CBE76A4F4C01\":\"https://sqs.us-east-2.amazonaws.com/***/auto-builder-stack-enhancedApp-stg-DOP-3977-queuesJobsQueue07E5CBE7-GKDjYx0Z0RAr\",\"ExportsOutputFnGetAttqueuesJobsQueue07E5CBE7Arn7C5C6E73\":\"arn:aws:sqs:us-east-2:***:auto-builder-stack-enhancedApp-stg-DOP-3977-queuesJobsQueue07E5CBE7-GKDjYx0Z0RAr\"},\"enhanced-vpc\":{\"ExportsOutputRefenhancedvpc381481FF879E0401\":\"vpc-0b2ae3b6e68611aee\",\"ExportsOutputRefenhancedvpcPrivateSubnet3Subnet3F2ABE77D0BEBCB1\":\"subnet-030765fd4d9f13c51\",\"ExportsOutputRefenhancedvpcPrivateSubnet2SubnetD80214313999429F\":\"subnet-09c0acca1ecd36a88\",\"ExportsOutputRefenhancedvpcPrivateSubnet1SubnetC8EBA1E0AF148179\":\"subnet-02e70b4724150ad1d\"},\"auto-builder-stack-enhancedApp-stg-DOP-3977-worker\":{\"ExportsOutputRefworkerclusterEBE39B1BB3E3095F\":\"auto-builder-stack-enhancedApp-stg-DOP-3977-worker-workerclusterEBE39B1B-0lta9vXFKdnW\"},\"auto-builder-stack-enhancedApp-stg-DOP-3977-webhooks\":{\"apiwebhookHandlersenhancedAppstgDOP3977Endpoint139ADC05\":\"https://ic72k49hp8.execute-api.us-east-2.amazonaws.com/prod/\"}}" >> outputs.json
      - name: Set CDK output into a variable
        id: cdk_output
        run: echo "cdk_json=$(cat cdk-infra/outputs.json)" >> $GITHUB_OUTPUT
      - name: Get Webhook URL
        id: webhook_url
        run: echo ${{ fromJson(steps.cdk_output.outputs.cdk_json).auto-builder-stack-enhancedApp-stg-DOP-3977-webhooks] }}
      # - name: Comment on PR
      #   run: gh pr comment ${{github.event.number}} 
